services:
  app:
    image: smart-sage-ai:1.1
    container_name: smart-sage-ai
    restart: unless-stopped
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"